server:
  port: 8081

spring:
  application:
    name: Auth-service

app:
  constant:
    keycloak:
      server_url: "http://localhost:8080"
      realm: "MyTestService-realm"
      client_id: "person-service"
      client_secret: "m3ljv2jj5B1mwlN3nq3P9jvD5OInTvFC"
    person_service:
      server_url: "http://localhost:8084"
