server:
  port: 8081

spring:
  application:
    name: Auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/MyTestService-realm

app:
  constant:
    keycloak:
      server-url: "http://localhost:8080"
      realm: "MyTestService-realm"
      client_id: "person-service"
      client_secret: "m3ljv2jj5B1mwlN3nq3P9jvD5OInTvFC"

      admin_username: "realmadmin"
      admin_password: "realmadmin"
    person_service:
      server-url: "http://localhost:8084"
